<?php
/**
 * CustomerParadigm_AmazonPersonalize
 *
 * @category   CustomerParadigm
 * @package    CustomerParadigm_AmazonPersonalize
 * @copyright  Copyright (c) 2023 Customer Paradigm (https://customerparadigm.com/)
 * @license    https://github.com/Customer-Paradigm/Amazon-Personalize/blob/master/LICENSE.md
 */
?>

<h3>Events</h3>
<script src="https://sdk.amazonaws.com/js/aws-sdk-2.573.0.min.js"></script>
<script>
    require([
        'jquery',
        'awsevents'
    ], function ($, script) {
    });
</script>
