<?php
/**
 * CustomerParadigm_AmazonPersonalize
 *
 * @category   CustomerParadigm
 * @package    CustomerParadigm_AmazonPersonalize
 * @copyright  Copyright (c) 2023 Customer Paradigm (https://customerparadigm.com/)
 * @license    https://github.com/Customer-Paradigm/Amazon-Personalize/blob/master/LICENSE.md
 */
?>
<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "wizardadvanced": {
                            "component": "CustomerParadigm_AmazonPersonalize/js/wizardprogress",
                    "template" : "CustomerParadigm_AmazonPersonalize/wizardtemplateadv",
                    "infoUrl" : "<?php echo($block->getImageUrl('info'))?>",
                    "ajaxResetUrl": "<?php echo($block->getAjaxResetUrl()) ?>",
                    "ajaxResetCampUrl": "<?php echo($block->getAjaxResetCampUrl()) ?>"
                        }
                    }
                }
            }
        }
</script>
<div data-bind="scope: 'wizardadvanced'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
