<?php
/**
 * CustomerParadigm_AmazonPersonalize
 *
 * @category   CustomerParadigm
 * @package    CustomerParadigm_AmazonPersonalize
 * @copyright  Copyright (c) 2023 Customer Paradigm (https://customerparadigm.com/)
 * @license    https://github.com/Customer-Paradigm/Amazon-Personalize/blob/master/LICENSE.md
 */
?>
<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "wizardprogress": {
                            "component": "CustomerParadigm_AmazonPersonalize/js/wizardprogress",
                            "template" : "CustomerParadigm_AmazonPersonalize/wizardtemplate",
                            "errUrl" : "<?php echo($block->getImageUrl('error'))?>",
                            "mediaUrl" : "<?php echo($block->getImageUrl('media'))?>",
                            "successUrl" : "<?php echo($block->getImageUrl('success'))?>",
                            "infoUrl" : "<?php echo($block->getImageUrl('info'))?>",
                            "refreshUrl" : "<?php echo($block->getImageUrl('refresh'))?>",
                            "processingUrl" : "<?php echo($block->getImageUrl('processing'))?>",
                            "pendingUrl" : "<?php echo($block->getImageUrl('pending'))?>",
                            "ajaxDisplayUrl": "<?php echo($block->getAjaxDisplayUrl()) ?>",
                            "ajaxRunUrl": "<?php echo($block->getAjaxRunUrl()) ?>",
                            "ajaxInteractionUrl": "<?php echo($block->getAjaxInteractionUrl()) ?>",
                            "ajaxAssetDisplayUrl": "<?php echo($block->getAjaxAssetDisplayUrl()) ?>",
                            "ajaxErrorlogUrl": "<?php echo($block->getAjaxErrorlogUrl()) ?>",
                            "ajaxErrorlogDownloadUrl": "<?php echo($block->getAjaxErrorlogDownloadUrl()) ?>",
                            "processStatus": "<?php echo($block->getProcessStatus()) ?>",
                            "needsInteractions": "<?php echo($block->needsInteractions()) ?>",
                            "interactionsCount": "<?php echo($block->interactionsCount() . ' of 1000') ?>",
                            "buttonMssg": "Start Process",
                            "steps": []
                        }
                    }
                }
            }
        }
</script>
<div data-bind="scope: 'wizardprogress'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
