<?php
/**
 * CustomerParadigm_AmazonPersonalize
 *
 * @category   CustomerParadigm
 * @package    CustomerParadigm_AmazonPersonalize
 * @copyright  Copyright (c) 2023 Customer Paradigm (https://customerparadigm.com/)
 * @license    https://github.com/Customer-Paradigm/Amazon-Personalize/blob/master/LICENSE.md
 */
/*
//Use to verify user id and a/b testing type page source
$userType = $block->getUserType();
$userid = $block->getUserId();
echo("<!-- Personalize User: $userid Type: $userType -->");
*/
$display = $block->canDisplay();
?>

<?php if ($display) { ?>
<div id='aws-display'>
<h3><?= $block->escapeHtml($block->getHeading()) ?></h3>
    <?= $block->getRecommendationHtml(); ?>
</div>
<?php } ?>
